<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net10.0-android;net10.0-ios</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Description>Push Notifications SDK for Android to send push notifications via AppAmbit platform.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/AppAmbit/appambit-sdk-dotnet</RepositoryUrl>
    <PackageTags>appambit; sdk; push; notifications; push-notifications; mobile; apps;</PackageTags>
    <Version>3.1.0</Version>
    <Authors>AppAmbit</Authors>
    <Company>AppAmbit</Company>
    <RootNamespace>AppAmbit.PushNotifications</RootNamespace>
    <AssemblyName>com.AppAmbit.PushNotifications</AssemblyName>
    <PackageId>com.AppAmbit.PushNotifications</PackageId>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Include="readme.md" Pack="true" PackagePath="\" />
    <None Include="icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="AppAmbit" />
  </ItemGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
    <SupportedOSPlatformVersion>21.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-ios'">
    <SupportedOSPlatformVersion>12.2</SupportedOSPlatformVersion>
  </PropertyGroup>

  <!-- Import targets for copying dynamic frameworks to app bundle -->
  <Import Project="AppAmbit.PushNotifications.targets" Condition="Exists('AppAmbit.PushNotifications.targets')" />

  <ItemGroup>
    <Compile Remove="Platforms\Android\**\*.cs" />
    <Compile Remove="Platforms\iOS\**\*.cs" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
    <AndroidMavenLibrary Include="com.appambit:appambit.push.notifications" Version="0.3.1" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
    <PackageReference Include="Xamarin.Firebase.Messaging" Version="123.2.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\sdk\AppAmbit\AppAmbit.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
    <Compile Include="Platforms\Android\**\*.cs" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-ios'">
    <Compile Include="Platforms\iOS\**\*.cs" />
  </ItemGroup>  

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-ios'">
    <!-- Simulator -->
    <NativeReference Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios' and $([MSBuild]::IsOSPlatform('osx')) and ($(RuntimeIdentifier.Contains('simulator')) or '$(RuntimeIdentifier)' == '')" Include="Platforms\iOS_Build\build\Debug-iphonesimulator\AppAmbitPushNotifications.framework">
        <Kind>Framework</Kind>
        <IsDynamic>True</IsDynamic>
        <SmartLink>True</SmartLink>
        <ForceLoad>True</ForceLoad>
    </NativeReference>
    <NativeReference Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios' and $([MSBuild]::IsOSPlatform('osx')) and ($(RuntimeIdentifier.Contains('simulator')) or '$(RuntimeIdentifier)' == '')" Include="Platforms\iOS_Build\build\Debug-iphonesimulator\AppAmbit.framework">
        <Kind>Framework</Kind>
        <IsDynamic>True</IsDynamic>
        <SmartLink>True</SmartLink>
        <ForceLoad>True</ForceLoad>
    </NativeReference>

    <!-- Device -->
    <NativeReference Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios' and $([MSBuild]::IsOSPlatform('osx')) and (!$(RuntimeIdentifier.Contains('simulator')) and '$(RuntimeIdentifier)' != '')" Include="Platforms\iOS_Build\build\Debug-iphoneos\AppAmbitPushNotifications.framework">
        <Kind>Framework</Kind>
        <IsDynamic>True</IsDynamic>
        <SmartLink>True</SmartLink>
        <ForceLoad>True</ForceLoad>
    </NativeReference>
    <NativeReference Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios' and $([MSBuild]::IsOSPlatform('osx')) and (!$(RuntimeIdentifier.Contains('simulator')) and '$(RuntimeIdentifier)' != '')" Include="Platforms\iOS_Build\build\Debug-iphoneos\AppAmbit.framework">
        <Kind>Framework</Kind>
        <IsDynamic>True</IsDynamic>
        <SmartLink>True</SmartLink>
        <ForceLoad>True</ForceLoad>
    </NativeReference>
  </ItemGroup>

</Project>
